/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AutorizariRouteImport } from './routes/autorizari'
import { Route as ComunicateRouteImport } from './routes/comunicate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DespreRouteImport } from './routes/despre'
import { Route as LegislatieRouteImport } from './routes/legislatie'
import { Route as UrgenteRouteImport } from './routes/urgente'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutorizariRoute = AutorizariRouteImport.update({
  id: '/autorizari',
  path: '/autorizari',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunicateRoute = ComunicateRouteImport.update({
  id: '/comunicate',
  path: '/comunicate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DespreRoute = DespreRouteImport.update({
  id: '/despre',
  path: '/despre',
  getParentRoute: () => rootRouteImport,
} as any)
const LegislatieRoute = LegislatieRouteImport.update({
  id: '/legislatie',
  path: '/legislatie',
  getParentRoute: () => rootRouteImport,
} as any)
const UrgenteRoute = UrgenteRouteImport.update({
  id: '/urgente',
  path: '/urgente',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/autorizari': typeof AutorizariRoute
  '/comunicate': typeof ComunicateRoute
  '/contact': typeof ContactRoute
  '/despre': typeof DespreRoute
  '/legislatie': typeof LegislatieRoute
  '/urgente': typeof UrgenteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/autorizari': typeof AutorizariRoute
  '/comunicate': typeof ComunicateRoute
  '/contact': typeof ContactRoute
  '/despre': typeof DespreRoute
  '/legislatie': typeof LegislatieRoute
  '/urgente': typeof UrgenteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/autorizari': typeof AutorizariRoute
  '/comunicate': typeof ComunicateRoute
  '/contact': typeof ContactRoute
  '/despre': typeof DespreRoute
  '/legislatie': typeof LegislatieRoute
  '/urgente': typeof UrgenteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/autorizari'
    | '/comunicate'
    | '/contact'
    | '/despre'
    | '/legislatie'
    | '/urgente'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/autorizari'
    | '/comunicate'
    | '/contact'
    | '/despre'
    | '/legislatie'
    | '/urgente'
  id:
    | '__root__'
    | '/'
    | '/autorizari'
    | '/comunicate'
    | '/contact'
    | '/despre'
    | '/legislatie'
    | '/urgente'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutorizariRoute: typeof AutorizariRoute
  ComunicateRoute: typeof ComunicateRoute
  ContactRoute: typeof ContactRoute
  DespreRoute: typeof DespreRoute
  LegislatieRoute: typeof LegislatieRoute
  UrgenteRoute: typeof UrgenteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autorizari': {
      id: '/autorizari'
      path: '/autorizari'
      fullPath: '/autorizari'
      preLoaderRoute: typeof AutorizariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunicate': {
      id: '/comunicate'
      path: '/comunicate'
      fullPath: '/comunicate'
      preLoaderRoute: typeof ComunicateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despre': {
      id: '/despre'
      path: '/despre'
      fullPath: '/despre'
      preLoaderRoute: typeof DespreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legislatie': {
      id: '/legislatie'
      path: '/legislatie'
      fullPath: '/legislatie'
      preLoaderRoute: typeof LegislatieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urgente': {
      id: '/urgente'
      path: '/urgente'
      fullPath: '/urgente'
      preLoaderRoute: typeof UrgenteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutorizariRoute: AutorizariRoute,
  ComunicateRoute: ComunicateRoute,
  ContactRoute: ContactRoute,
  DespreRoute: DespreRoute,
  LegislatieRoute: LegislatieRoute,
  UrgenteRoute: UrgenteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
