/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AutorizariRouteImport } from './routes/autorizari'
import { Route as ComunicateRouteImport } from './routes/comunicate'
import { Route as ConstructiiNucleareRouteImport } from './routes/constructii-nucleare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DespreRouteImport } from './routes/despre'
import { Route as InstalatiiNucleareRouteImport } from './routes/instalatii-nucleare'
import { Route as Legea111RouteImport } from './routes/legea-111'
import { Route as LegislatieRouteImport } from './routes/legislatie'
import { Route as ManagementulCalitatiiRouteImport } from './routes/managementul-calitatii'
import { Route as SurseDeRadiatiiIonizanteRouteImport } from './routes/surse-de-radiatii-ionizante'
import { Route as TransportMaterialeRadioactiveRouteImport } from './routes/transport-materiale-radioactive'
import { Route as UrgenteRouteImport } from './routes/urgente'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutorizariRoute = AutorizariRouteImport.update({
  id: '/autorizari',
  path: '/autorizari',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunicateRoute = ComunicateRouteImport.update({
  id: '/comunicate',
  path: '/comunicate',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructiiNucleareRoute = ConstructiiNucleareRouteImport.update({
  id: '/constructii-nucleare',
  path: '/constructii-nucleare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DespreRoute = DespreRouteImport.update({
  id: '/despre',
  path: '/despre',
  getParentRoute: () => rootRouteImport,
} as any)
const InstalatiiNucleareRoute = InstalatiiNucleareRouteImport.update({
  id: '/instalatii-nucleare',
  path: '/instalatii-nucleare',
  getParentRoute: () => rootRouteImport,
} as any)
const Legea111Route = Legea111RouteImport.update({
  id: '/legea-111',
  path: '/legea-111',
  getParentRoute: () => rootRouteImport,
} as any)
const LegislatieRoute = LegislatieRouteImport.update({
  id: '/legislatie',
  path: '/legislatie',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementulCalitatiiRoute = ManagementulCalitatiiRouteImport.update({
  id: '/managementul-calitatii',
  path: '/managementul-calitatii',
  getParentRoute: () => rootRouteImport,
} as any)
const SurseDeRadiatiiIonizanteRoute =
  SurseDeRadiatiiIonizanteRouteImport.update({
    id: '/surse-de-radiatii-ionizante',
    path: '/surse-de-radiatii-ionizante',
    getParentRoute: () => rootRouteImport,
  } as any)
const TransportMaterialeRadioactiveRoute =
  TransportMaterialeRadioactiveRouteImport.update({
    id: '/transport-materiale-radioactive',
    path: '/transport-materiale-radioactive',
    getParentRoute: () => rootRouteImport,
  } as any)
const UrgenteRoute = UrgenteRouteImport.update({
  id: '/urgente',
  path: '/urgente',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/autorizari': typeof AutorizariRoute
  '/comunicate': typeof ComunicateRoute
  '/constructii-nucleare': typeof ConstructiiNucleareRoute
  '/contact': typeof ContactRoute
  '/despre': typeof DespreRoute
  '/instalatii-nucleare': typeof InstalatiiNucleareRoute
  '/legea-111': typeof Legea111Route
  '/legislatie': typeof LegislatieRoute
  '/managementul-calitatii': typeof ManagementulCalitatiiRoute
  '/surse-de-radiatii-ionizante': typeof SurseDeRadiatiiIonizanteRoute
  '/transport-materiale-radioactive': typeof TransportMaterialeRadioactiveRoute
  '/urgente': typeof UrgenteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/autorizari': typeof AutorizariRoute
  '/comunicate': typeof ComunicateRoute
  '/constructii-nucleare': typeof ConstructiiNucleareRoute
  '/contact': typeof ContactRoute
  '/despre': typeof DespreRoute
  '/instalatii-nucleare': typeof InstalatiiNucleareRoute
  '/legea-111': typeof Legea111Route
  '/legislatie': typeof LegislatieRoute
  '/managementul-calitatii': typeof ManagementulCalitatiiRoute
  '/surse-de-radiatii-ionizante': typeof SurseDeRadiatiiIonizanteRoute
  '/transport-materiale-radioactive': typeof TransportMaterialeRadioactiveRoute
  '/urgente': typeof UrgenteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/autorizari': typeof AutorizariRoute
  '/comunicate': typeof ComunicateRoute
  '/constructii-nucleare': typeof ConstructiiNucleareRoute
  '/contact': typeof ContactRoute
  '/despre': typeof DespreRoute
  '/instalatii-nucleare': typeof InstalatiiNucleareRoute
  '/legea-111': typeof Legea111Route
  '/legislatie': typeof LegislatieRoute
  '/managementul-calitatii': typeof ManagementulCalitatiiRoute
  '/surse-de-radiatii-ionizante': typeof SurseDeRadiatiiIonizanteRoute
  '/transport-materiale-radioactive': typeof TransportMaterialeRadioactiveRoute
  '/urgente': typeof UrgenteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/autorizari'
    | '/comunicate'
    | '/constructii-nucleare'
    | '/contact'
    | '/despre'
    | '/instalatii-nucleare'
    | '/legea-111'
    | '/legislatie'
    | '/managementul-calitatii'
    | '/surse-de-radiatii-ionizante'
    | '/transport-materiale-radioactive'
    | '/urgente'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/autorizari'
    | '/comunicate'
    | '/constructii-nucleare'
    | '/contact'
    | '/despre'
    | '/instalatii-nucleare'
    | '/legea-111'
    | '/legislatie'
    | '/managementul-calitatii'
    | '/surse-de-radiatii-ionizante'
    | '/transport-materiale-radioactive'
    | '/urgente'
  id:
    | '__root__'
    | '/'
    | '/autorizari'
    | '/comunicate'
    | '/constructii-nucleare'
    | '/contact'
    | '/despre'
    | '/instalatii-nucleare'
    | '/legea-111'
    | '/legislatie'
    | '/managementul-calitatii'
    | '/surse-de-radiatii-ionizante'
    | '/transport-materiale-radioactive'
    | '/urgente'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutorizariRoute: typeof AutorizariRoute
  ComunicateRoute: typeof ComunicateRoute
  ConstructiiNucleareRoute: typeof ConstructiiNucleareRoute
  ContactRoute: typeof ContactRoute
  DespreRoute: typeof DespreRoute
  InstalatiiNucleareRoute: typeof InstalatiiNucleareRoute
  Legea111Route: typeof Legea111Route
  LegislatieRoute: typeof LegislatieRoute
  ManagementulCalitatiiRoute: typeof ManagementulCalitatiiRoute
  SurseDeRadiatiiIonizanteRoute: typeof SurseDeRadiatiiIonizanteRoute
  TransportMaterialeRadioactiveRoute: typeof TransportMaterialeRadioactiveRoute
  UrgenteRoute: typeof UrgenteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autorizari': {
      id: '/autorizari'
      path: '/autorizari'
      fullPath: '/autorizari'
      preLoaderRoute: typeof AutorizariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunicate': {
      id: '/comunicate'
      path: '/comunicate'
      fullPath: '/comunicate'
      preLoaderRoute: typeof ComunicateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constructii-nucleare': {
      id: '/constructii-nucleare'
      path: '/constructii-nucleare'
      fullPath: '/constructii-nucleare'
      preLoaderRoute: typeof ConstructiiNucleareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despre': {
      id: '/despre'
      path: '/despre'
      fullPath: '/despre'
      preLoaderRoute: typeof DespreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instalatii-nucleare': {
      id: '/instalatii-nucleare'
      path: '/instalatii-nucleare'
      fullPath: '/instalatii-nucleare'
      preLoaderRoute: typeof InstalatiiNucleareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legea-111': {
      id: '/legea-111'
      path: '/legea-111'
      fullPath: '/legea-111'
      preLoaderRoute: typeof Legea111RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legislatie': {
      id: '/legislatie'
      path: '/legislatie'
      fullPath: '/legislatie'
      preLoaderRoute: typeof LegislatieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/managementul-calitatii': {
      id: '/managementul-calitatii'
      path: '/managementul-calitatii'
      fullPath: '/managementul-calitatii'
      preLoaderRoute: typeof ManagementulCalitatiiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surse-de-radiatii-ionizante': {
      id: '/surse-de-radiatii-ionizante'
      path: '/surse-de-radiatii-ionizante'
      fullPath: '/surse-de-radiatii-ionizante'
      preLoaderRoute: typeof SurseDeRadiatiiIonizanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport-materiale-radioactive': {
      id: '/transport-materiale-radioactive'
      path: '/transport-materiale-radioactive'
      fullPath: '/transport-materiale-radioactive'
      preLoaderRoute: typeof TransportMaterialeRadioactiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urgente': {
      id: '/urgente'
      path: '/urgente'
      fullPath: '/urgente'
      preLoaderRoute: typeof UrgenteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutorizariRoute: AutorizariRoute,
  ComunicateRoute: ComunicateRoute,
  ConstructiiNucleareRoute: ConstructiiNucleareRoute,
  ContactRoute: ContactRoute,
  DespreRoute: DespreRoute,
  InstalatiiNucleareRoute: InstalatiiNucleareRoute,
  Legea111Route: Legea111Route,
  LegislatieRoute: LegislatieRoute,
  ManagementulCalitatiiRoute: ManagementulCalitatiiRoute,
  SurseDeRadiatiiIonizanteRoute: SurseDeRadiatiiIonizanteRoute,
  TransportMaterialeRadioactiveRoute: TransportMaterialeRadioactiveRoute,
  UrgenteRoute: UrgenteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
